# Site settings
title: "Coding: A Girl's (amateur) Perspective"
header-img: img/home-bg.png
email: manda.panda91@yahoo.com
copyright_name: amandena
description: > # this means to ignore newlines until "baseurl:"
  Thoughts Upon Thoughts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  amandena
learn_profile: amandena
email_username: manda.panda91@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
